#SPDX-License-Identifier: MIT-0
---
# tasks file for docker


- block:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
    
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
    
    - name: Add Docker GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
      args:
        creates: /usr/share/keyrings/docker.gpg

    
    - name: Add Docker repository
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: "{{ ansible_distribution_release }}"
        components:
          - stable
        architectures: amd64
        signed_by: /usr/share/keyrings/docker.gpg
        when: ansible_distribution in ['Debian', 'Ubuntu']
      
    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
    
    - name: add docker group
      ansible.builtin.group:
        name: docker
        state: present
    
    - name: Add Ansible user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: restart connection to apply group changes
      ansible.builtin.meta: reset_connection

  become: true

- name: refresh user groups
  ansible.builtin.command: newgrp docker
